name: markdown_editable_textinput
description: A TextField Widget that allow you to convert easily what's in the TextField to Markdown.
version: 2.0.2
homepage: https://github.com/playmoweb/markdown-editable-textinput
repository: https://github.com/playmoweb/markdown-editable-textinput

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  effective_dart: ^1.3.1
  expandable: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
